local plugin = require("plugin")

describe("plugin", function()
  it("setup() merges options into config", function()
    plugin.setup({ foo = "bar" })
    assert.equals("bar", plugin.config.foo)
  end)

  it("registers its user command", function()
    plugin.setup({})
    local cmds = vim.api.nvim_get_commands({})
    assert.is_truthy(cmds[plugin.command])
  end)
end)

describe("notes", function()
  it("list_md_files returns sorted *.md in a dir", function()
    local notes = require("plugin.notes")
    local tmp = vim.fn.tempname()
    vim.fn.mkdir(tmp, "p")
    vim.fn.writefile({ "# b" }, tmp .. "/b.md")
    vim.fn.writefile({ "# a" }, tmp .. "/a.md")
    vim.fn.writefile({ "x" }, tmp .. "/ignored.txt")
    assert.same({ "a.md", "b.md" }, notes.list_md_files(tmp))
  end)
end)